[package]
name = "seedsplit"
version = "0.1.0"
description = "Split and/or rebuild a seedphrase"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
clap = { version = "3.0", features = ["derive"] }